### ISSUE TITLE
Update width of schema reference page

### ISSUE THREAD

**Issue by timgdavies** [openownership/data-standard-sphinx-theme#37]
For the schema reference page, we need a bit more width.

Ideally changing, for this page only, from 42 to 62rem:

```css
.oods-main {
    max-width: 62rem;
    margin: 0 auto;
}
```
